export const products = [
    {
        id: 1,
        title: "Kuncit Kacang",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052366/KRIDHASARI-FIKS/iyz8wddgsoegegnbvlvd.png",
        price: 15000,
        description: "Geti kacang tanah dengan caramel yang dikemas dalam plastik kuncit.",
        category: "Camilan",
    },
    {
        id: 2,
        title: "Gethi Gula Jawa",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052375/KRIDHASARI-FIKS/eho2om1mvdwpbv5qe5dh.png",
        price: 15000,
        description: "Enting-enting berbahan kacang tanah dan gula jawa yang dikemas dengan plastik kuncit.",
        category: "Camilan",
    },
    {
        id: 3,
        title: "Kuncit Wijen",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052381/KRIDHASARI-FIKS/dliuhatnosngbw6i4orj.png",
        price: 15000,
        description: "Geti wijen legit yang dikemas dalam plastik kuncit.",
        category: "Camilan",
    },
    {
        id: 4,
        title: "Kotak Kacang",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052390/KRIDHASARI-FIKS/bzremjhwzwkcajyib1nb.png",
        price: 15000,
        description: "Geti kacang berbentuk kotak kecil yang dikemas dalam plastik press berbentuk kotak.",
        category: "Camilan",
    },
    {
        id: 5,
        title: "Toples Gethi Bola Kacang",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052396/KRIDHASARI-FIKS/pnfynqad9gswjpmxfdc0.png",
        price: 15000,
        description: "Varian geti kacang tanah berbentuk bola-bola kecil yang dikemas dalam toples.",
        category: "Camilan",
    },
    {
        id: 6,
        title: "Kotak Wijen",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052400/KRIDHASARI-FIKS/f6fadcwybo73xh3glj80.png",
        price: 15000,
        description: "Geti wijen berbentuk kotak kecil yang dikemas dalam plastik press berbentuk kotak.",
        category: "Camilan",
    },
    {
        id: 7,
        title: "Bantal Kacang",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052404/KRIDHASARI-FIKS/gpn0j3snb8ol6ynl18ij.png",
        price: 15000,
        description: "Camilan berbahan kacang tanah yang manis dengan gula karamel, dikemas dengan bentuk plastik bantal.",
        category: "Camilan",
    },
    {
        id: 8,
        title: "Toples Gethi Bola Wijen",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052410/KRIDHASARI-FIKS/ilissnx8bn55gyrjdtug.png",
        price: 15000,
        description: "Varian geti wijen berbentuk bola-bola kecil yang dikemas dalam toples.",
        category: "Camilan",
    },
    {
        id: 9,
        title: "Bantal Wijen",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052416/KRIDHASARI-FIKS/eevxstgh7wmxiwylbaak.png",
        price: 15000,
        description: "Geti dengan bahan wijen, rasa yang manis legit, dikemas dalam bentuk plastik bantal.",
        category: "Camilan",
    },
    {
        id: 10,
        title: "Toples Mix",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052421/KRIDHASARI-FIKS/bqknackvqf2res9kctfb.png",
        price: 15000,
        description: "Geti kacang tanah dan wijen dalam satu kemasan toples berbentuk tabung tinggi.",
        category: "Camilan",
    },
    {
        id: 11,
        title: "Bulat Besar Wijen",  
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052429/KRIDHASARI-FIKS/d0e1ozjay7sq5bou0bni.png",
        price: 15000,
        description: "Geti berbahan wijen yang dikemas dalam toples bulat jumbo.",
        category: "Camilan",
    },
    {
        id: 12,
        title: "Bulat Kecil Kacang",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052435/KRIDHASARI-FIKS/ob9f8vivanbdglcxnkpb.png",
        price: 15000,
        description: "Geti kacang tanah yang dikemas dalam toples bening yang bulat berdiameter lebih kecil.",
        category: "Camilan",
    },
    {
        id: 13,
        title: "Bulat Kecil Wijen",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052441/KRIDHASARI-FIKS/wfkxki7hyh62jgtmtx3w.png",
        price: 15000,
        description: "Geti wijen legit yang dikemas dalam toples bening bulat berdiameter lebih kecil.",
        category: "Camilan",
    },
    {
        id: 14,
        title: "Bulat Mix",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052449/KRIDHASARI-FIKS/o2yszewtjimb3lfhepn9.png",
        price: 15000,
        description: "Campuran antara geti kacang tanah dan wijen yang dikemas dalam toples bening bulat.",
        category: "Camilan",
    },
    {
        id: 15,
        title: "Bulat Besar Kacang",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052474/KRIDHASARI-FIKS/q7dt7k0epblrlptzoeo5.png",
        price: 15000,
        description: "Geti kacang tanah dalam kemasan toples bulat besar.",
        category: "Camilan",
    },
    {
        id: 16,
        title: "Enting Gethi Mix",
        image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1741052484/KRIDHASARI-FIKS/d7dckgjmsqea6qn4h2hu.png",
        price: 15000,
        description: "Varian geti coklat, blimbing, dan original dengan kemasan box kecil.",
        category: "Camilan",
    }
]