export const products = [
    {
    id: 1,
    title: "Kuncit-Kacang",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431732/KRIDHASARI/lhwct0nsijpjnsdbij6m.png",
    price: 15000,
    description: "Enting-enting berbahan kacang tanah dan gula jawa yang dikemas dengan plastik kuncit",
    category: "Camilan",
},
{
    id: 2,
    title: "Kuncit-Wijen",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431731/KRIDHASARI/g3gtjmdsidpfey4uuhjq.png",
    price: 15000,
    description: "Enting-enting berbahan Wijen dan gula jawa yang dikemas dengan plastik kuncit",
    category: "Camilan",
},
{
    id: 3,
    title: "Kotak-Kacang",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431730/KRIDHASARI/evu5tgmkd9tf1xpenhte.png",
    price: 15000,
    description: "Geti kacang berbentuk bola-bola kecil yang dikemas dalam plastik press berbentuk kotak.",
    category: "Camilan",
},
{
    id: 4,
    title: "Kotak-Wijen",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431730/KRIDHASARI/nyvqg4denph5xsubuucr.png",
    price: 15000,
    description: "Geti wijen yang berbentuk bola-bola kecil, dikemas dengan plastik yang dipress dan berbentuk kotak",
    category: "Camilan",
},{
    id: 5,
    title: "Gethi-Gula-Jawa",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431730/KRIDHASARI/usul4e6zckzlshsfxzl1.png",
    price: 15000,
    description: "Enting-enting berbahan kacang tanah dan gula jawa yang dikemas dengan plastik kuncit.",
    category: "Camilan",
},{
    id: 6,
    title: "Toples-Gethi-Mix",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431727/KRIDHASARI/wzjoxlsgfudeivj7bgxx.png",
    price: 15000,
    description: "Campuran antara geti kacang tanah dan wijen yang dikemas dalam toples bening bulat",
    category: "Camilan",
},{
    id: 7,
    title: "Toples-Bulat-Besar-Kacang",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431725/KRIDHASARI/dfbsbkrewikdx7gf1rk4.png",
    price: 15000,
    description: "Geti kacang tanah dalam kemasan toples bulat besar",
    category: "Camilan",
},{
    id: 8,
    title: "Toples-Bulat-Kecil-Kacang",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431725/KRIDHASARI/qnf4dru52epllwcok8nm.png",
    price: 15000,
    description: "Geti kacang tanah yang dikemas dalam toples bening yang bulat berdiameter lebih kecil",
    category: "Camilan",
},{
    id: 9,
    title: "Toples-Kacang",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431724/KRIDHASARI/sdbealpuuchs13kre01v.png",
    price: 15000,
    description: "Varian geti kacang tanah yang dikemas dalam toples dengan tutup hitam",
    category: "Camilan",
},{
    id: 10,
    title: "Toples-Bulat-Besar-Wijen",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431724/KRIDHASARI/klldcbokmo89znfkyjzq.png",
    price: 15000,
    description: "Geti berbahan wijen yang dikemas dalam toples bulat jumbo",
    category: "Camilan",
},{
    id: 11,
    title: "Toples-Gethi-Bola-Wijen",  
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431724/KRIDHASARI/yqzcsaug7yzzxxoy4npq.png",
    price: 15000,
    description: "Varian geti wijen berbentuk bola-bola kecil yang dikemas dalam toples",
    category: "Camilan",
},{
    id: 12,
    title: "Bulat-Kecil-Wijen",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431717/KRIDHASARI/yqxtle92h6xdqbr4raor.png",
    price: 15000,
    description: "Geti wijen legit yang dikemas dalam toples bening bulat berdiameter lebih kecil",
    category: "Camilan",
},{
    id: 13,
    title: "Bantal-Kacang",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431716/KRIDHASARI/zsg3rewryffg5u4dfekl.png",
    price: 15000,
    description: "Camilan berbahan kacang tanah yang manis dengan gula karamel, dikemas dengan bentuk plastik bantal",
    category: "Camilan",
},{
    id: 14,
    title: "Toples-Gethi-Bola-Kacang",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431716/KRIDHASARI/jwqcpfdc5ufuswzenpxq.png",
    price: 15000,
    description: "Varian geti kacang tanah berbentuk bola-bola kecil yang dikemas dalam toples",
    category: "Camilan",
},{
    id: 15,
    title: "Bantal-Wijen",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431716/KRIDHASARI/snaun5o6gpjlayh7g2qk.png",
    price: 15000,
    description: "Geti dengan bahan wijen, rasa yang manis legit, dikemas dalam bentuk plastik bantal",
    category: "Camilan",
},{
    id: 16,
    title: "Enting-Gethi-Mix",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431716/KRIDHASARI/eh3k2myj425y6zzemspq.png",
    price: 15000,
    description: "Geti kacang tanah dan wijen dalam satu kemasan toples berbentuk tabung tinggi",
    category: "Camilan",
},{
    id: 17,
    title: "Toples-Gethi-Bola-Wijen",
    image: "https://res.cloudinary.com/dvibi1dg9/image/upload/v1739431716/KRIDHASARI/norzcctb8rs9d738lr0v.png", 
    price: 15000,
    description: "Varian geti wijen berbentuk bola-bola kecil yang dikemas dalam toples",
    category: "Camilan",
}
]
